// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlybynsxxrjbdedroizp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJseWJ5bnN4eHJqYmRlZHJvaXpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2ODI5NDQsImV4cCI6MjA3MTI1ODk0NH0.WUSrLD3NE-Oar-mHAf85rQ_NnubKfAqt_zy1h8_8qBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});